### ISSUE TITLE
Fatal: Remote branch vue not found in upstream origin

### ISSUE THREAD

**Issue by davidbe** [David-Development/nextcloud-dev-docker#5]
I follow the instructions for linux, but when I try:

`git clone -b vue https://github.com/nextcloud/contacts.git`

I get:

`Cloning into 'contacts'...
fatal: Remote branch vue not found in upstream origin`

How can we resolve this issue?
Edit: Not cloning from specific branch? Why was this in the doc?

**Comment by David-Development** [comment]
@davidbe Thanks for pointing this out and sorry for the delay. Indeed the docs were a little outdated. When we created this development container, the vue branch was the one where all the up-to-date work was being done on. As it was merged into master at some point it doesn't exist anymore. I adjusted the Readme accordingly. Thanks you!
